# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20161228_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('description', models.CharField(max_length=100, verbose_name='answer')),
                ('points', models.PositiveSmallIntegerField(verbose_name='value')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('description', models.CharField(max_length=200, verbose_name='question')),
                ('sort_order', models.PositiveSmallIntegerField(default=1, verbose_name='sort order')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country', verbose_name='country')),
            ],
            options={
                'default_permissions': [],
                'permissions': (('admin_add_quiz_question', 'ADMIN: Can add quiz question'), ('admin_change_quiz_question', 'ADMIN: Can change quiz question'), ('admin_delete_quiz_question', 'ADMIN: Can delete quiz question'), ('admin_view_quiz_question', 'ADMIN: Can view quiz questions')),
            },
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='quiz_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizQuestion', verbose_name='question'),
        ),
    ]
