# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 14:09
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import wannamigrate.core.util


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170402_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='photo',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=wannamigrate.core.util.CustomUploadToAutoSlugClassNameDir('description'), verbose_name='photo'),
        ),
    ]
