# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-24 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170402_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizanswer',
            options={'default_permissions': [], 'ordering': ['id']},
        ),
    ]
