# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import wannamigrate.core.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20170330_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='is enabled')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1, verbose_name='sort order')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country', verbose_name='country')),
            ],
            options={
                'default_permissions': [],
                'permissions': (('admin_add_chapter', 'ADMIN: Can add chapter'), ('admin_change_chapter', 'ADMIN: Can change chapter'), ('admin_delete_chapter', 'ADMIN: Can delete chapter'), ('admin_view_chapter', 'ADMIN: Can view chapters')),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('html_content', models.TextField(verbose_name='html content')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='is enabled')),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to=wannamigrate.core.util.CustomUploadToAutoSlugClassNameDir('title'), verbose_name='image')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1, verbose_name='sort order')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Chapter', verbose_name='chapter')),
            ],
            options={
                'default_permissions': [],
                'permissions': (('admin_add_section', 'ADMIN: Can add section'), ('admin_change_section', 'ADMIN: Can change section'), ('admin_delete_section', 'ADMIN: Can delete section'), ('admin_view_section', 'ADMIN: Can view sections')),
            },
        ),
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='section_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.SectionCategory', verbose_name='category'),
        ),
    ]
