# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20170428_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='slug',
        ),
    ]
