# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_member_quiz_answers'),
        ('core', '0003_auto_20170330_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('display_name', models.CharField(max_length=30, verbose_name='display name')),
                ('description', models.TextField(verbose_name='description')),
                ('total_views', models.PositiveSmallIntegerField(default=0, verbose_name='total views')),
                ('total_replies', models.PositiveSmallIntegerField(default=0, verbose_name='total replies')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country', verbose_name='country')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member', verbose_name='member')),
            ],
            options={
                'default_permissions': [],
                'permissions': (('admin_add_discussion', 'ADMIN: Can add discussion'), ('admin_change_discussion', 'ADMIN: Can change discussion'), ('admin_delete_discussion', 'ADMIN: Can delete discussion'), ('admin_view_discussion', 'ADMIN: Can view discussions')),
            },
        ),
        migrations.CreateModel(
            name='DiscussionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.Discussion', verbose_name='discussion')),
            ],
            options={
                'default_permissions': [],
                'permissions': (('admin_add_discussion_question', 'ADMIN: Can add discussion question'), ('admin_change_discussion_question', 'ADMIN: Can change discussion question'), ('admin_delete_discussion_question', 'ADMIN: Can delete discussion question'), ('admin_view_discussion_question', 'ADMIN: Can view discussion questions')),
            },
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('description', models.TextField(verbose_name='description')),
                ('total_upvotes', models.PositiveSmallIntegerField(default=0, verbose_name='total upvotes')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.Discussion', verbose_name='discussion')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member', verbose_name='member')),
            ],
            options={
                'default_permissions': [],
                'permissions': (('admin_add_discussion_reply', 'ADMIN: Can add discussion reply'), ('admin_change_discussion_reply', 'ADMIN: Can change discussion reply'), ('admin_delete_discussion_reply', 'ADMIN: Can delete discussion reply'), ('admin_view_discussion_reply', 'ADMIN: Can view discussion replies')),
            },
        ),
    ]
