# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-20 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='content_modified_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='modified date'),
            preserve_default=False,
        ),
    ]
