# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-22 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_discussion_content_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='content_modified_date',
            field=models.DateTimeField(verbose_name='modified date'),
        ),
    ]
