# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-22 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_quiz_answers'),
        ('discussion', '0003_auto_20170722_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionReplyUpvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('discussion_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.DiscussionReply', verbose_name='discussion reply')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member', verbose_name='member')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.RemoveField(
            model_name='discussionquestion',
            name='discussion',
        ),
        migrations.DeleteModel(
            name='DiscussionQuestion',
        ),
    ]
