# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-26 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_auto_20170722_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='display_name',
        ),
    ]
