# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-01 08:04
from __future__ import unicode_literals
from django.conf import settings
from django.db import migrations


def doc_group_initial_values(apps, schema_editor):

    # Get model to use (historical version)
    DocGroup = apps.get_model("doc", "DocGroup")

    doc_group = DocGroup()
    doc_group.name = 'Proof of English Skills'
    doc_group.is_enabled = True
    doc_group.sort_order = 1
    doc_group.country_id = settings.DB_ID_COUNTRY_AUSTRALIA
    doc_group.save()

    doc_group = DocGroup()
    doc_group.name = 'Proof of "Genuine Temporary Entrant" Condition'
    doc_group.is_enabled = True
    doc_group.sort_order = 2
    doc_group.country_id = settings.DB_ID_COUNTRY_AUSTRALIA
    doc_group.save()

    doc_group = DocGroup()
    doc_group.name = 'Proof of Financial Funds'
    doc_group.is_enabled = True
    doc_group.sort_order = 3
    doc_group.country_id = settings.DB_ID_COUNTRY_AUSTRALIA
    doc_group.save()

    doc_group = DocGroup()
    doc_group.name = 'Proof of Educational Degree'
    doc_group.is_enabled = True
    doc_group.sort_order = 4
    doc_group.country_id = settings.DB_ID_COUNTRY_AUSTRALIA
    doc_group.save()

    doc_group = DocGroup()
    doc_group.name = 'Proof of Married or De-Facto Partner'
    doc_group.is_enabled = True
    doc_group.sort_order = 5
    doc_group.country_id = settings.DB_ID_COUNTRY_AUSTRALIA
    doc_group.save()

    doc_group = DocGroup()
    doc_group.name = 'Proof of Work Experience'
    doc_group.is_enabled = True
    doc_group.sort_order = 6
    doc_group.country_id = settings.DB_ID_COUNTRY_AUSTRALIA
    doc_group.save()

    doc_group = DocGroup()
    doc_group.name = 'Job Hunting and Professional Profile'
    doc_group.is_enabled = True
    doc_group.sort_order = 7
    doc_group.country_id = settings.DB_ID_COUNTRY_AUSTRALIA
    doc_group.save()

    doc_group = DocGroup()
    doc_group.name = 'Proof of Police Clearance'
    doc_group.is_enabled = True
    doc_group.sort_order = 8
    doc_group.country_id = settings.DB_ID_COUNTRY_AUSTRALIA
    doc_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(doc_group_initial_values),
    ]
