# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-01 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_auto_20170701_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='doc_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.DocGroup', verbose_name='doc group'),
        ),
    ]
