# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Virtual Machine Box
  config.vm.box = "ubuntu/trusty32"

  config.vm.synced_folder "../app", "/www"
  config.vm.synced_folder "./config", "/infra/config"
  config.vm.synced_folder "./scripts", "/infra/scripts"
  #config.vm.synced_folder "./scripts", "/home/vagrant/scripts"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision :shell, :inline => "sudo bash /infra/scripts/configure.sh"

end
