"""
Django settings for the wannamigrate project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import pytz
from celery.schedules import crontab
from django.utils.translation import ugettext_lazy as _
from .local import *


#########################################
# GENERAL SYSTEM CONFIGURATIONS
#########################################
# Base app path
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# URLs
if IS_PROD:
    BASE_URL = 'https://www.wannamigrate.com'
    BASE_URL_SECURE = 'https://www.wannamigrate.com'
else:
    BASE_URL = 'http://localhost:8087'
    BASE_URL_SECURE = 'http://localhost:8087'

# Access restrictions
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "wannamigrate.com",
    "www.wannamigrate.com",
    "52.221.243.179"
]

INTERNAL_IPS = (
    "localhost",
    "127.0.0.1",
    "52.221.243.179"
)

# Path of wsgi app
WSGI_APPLICATION = 'wannamigrate.wsgi.application'

# The base URL Conf
ROOT_URLCONF = 'wannamigrate.urls'


#########################################
# INTERNATIONALIZATION AND LOCALIZATION
#########################################
LANGUAGES = (
    ('en', _('English')),
    ('pt', _('Portuguese')),
)

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Australia/Sydney'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = False

LOCALE_PATHS = (
    os.path.join(BASE_DIR, '..', 'locale'),
)


#########################################
# PATHS FOR STATIC, UPLOAD and TEMPLATES
#########################################
# Global UPLOAD folder
MEDIA_ROOT = os.path.join(BASE_DIR, '..', 'upload')
MEDIA_URL = '/upload/'

# Static Files paths
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, '..', "static")


#########################################
# AUTH SETTINGS
#########################################
AUTH_USER_MODEL = 'core.User'
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'wannamigrate.core.auth_backends.AdminBackend',
)


#########################################
# TEMPLATE SETTINGS
#########################################

# Template Context Processors
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, '..', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wannamigrate.core.context_processors.add_global_template_data'
            ],
        },
    },
]


#########################################
# MIDDLEWARES
#########################################
MIDDLEWARE_CLASSES = (
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)


#########################################
# DJANGO APPS REQUIRED
#########################################
# Application definition
DEFAULT_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)
THIRD_PARTY_APPS = (
    'stdimage',
    'compressor',
)
LOCAL_APPS = (
    'wannamigrate.core',
    'wannamigrate.landing',
    'wannamigrate.company',
    'wannamigrate.member',
    'wannamigrate.order',
)

INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY_APPS + LOCAL_APPS


#########################################
# COMPRESSOR SETTINGS (for static css and js)
#########################################
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True
COMPRESS_CSS_FILTERS = (
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.rCSSMinFilter'
)
COMPRESS_STORAGE = 'compressor.storage.GzipCompressorFileStorage'
HTML_MINIFY = True
EXCLUDE_FROM_MINIFYING = ('/admin/')


#########################################
# LOGGING / DEBUG SETTINGS
#########################################
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'formatter': 'verbose',
            'class': 'logging.FileHandler',
            'filename': '/wannamigrate/debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}


#########################################
# CELERY SETTINGS
#########################################
CELERY_TIMEZONE = 'Australia/Sydney'
if IS_PROD:
    CELERYBEAT_SCHEDULE = {}


#########################################
# WANNAMIGRATE APP SETTINGS
#########################################

# Model choices
GENDER_CHOICES = (
    ('F', _('Female')),
    ('M', _('Male'))
)
BOOLEAN_CHOICES = (
    (True, _('Yes')),
    (False, _('No'))
)
TIMEZONES = [(tz, tz) for tz in pytz.common_timezones]

# DB IDS - Countries
DB_ID_COUNTRY_AUSTRALIA = 117

# DB IDS - Payment Types
DB_ID_PAYMENT_TYPE_STRIPE_CARDS = 1
DB_ID_PAYMENT_TYPE_PAYPAL_CARDS = 2

# DB IDS - Order Status
DB_ID_ORDER_STATUS_AWAITING_PAYMENT = 1
DB_ID_ORDER_STATUS_AUTHORISED_WAITING = 2
DB_ID_ORDER_STATUS_CHARGED_SUCCEEDED = 3
DB_ID_ORDER_STATUS_CHARGED_FAILED = 4
DB_ID_ORDER_STATUS_CHARGED_REFUNDED = 5
DB_ID_ORDER_STATUS_AWAITING_AUTHORISATION = 6

# DB IDS - Subscription Status
DB_ID_SUBSCRIPTION_STATUS_NEVER_ACTIVATED = 1
DB_ID_SUBSCRIPTION_STATUS_ACTIVE = 2
DB_ID_SUBSCRIPTION_STATUS_EXPIRED = 3
DB_ID_SUBSCRIPTION_STATUS_CANCELLED = 4
DB_ID_SUBSCRIPTION_STATUS_SKIP = 5
DB_ID_SUBSCRIPTION_STATUS_PAUSE = 6

# EMAIL SETTINGS
EMAIL_DEFAULT_TO_ADDRESS = 'hello@humbertomn.com'
EMAIL_DEFAULT_FROM_ADDRESS = 'humberto@wannamigrate.com'
EMAIL_DEFAULT_FROM_NAME = 'Wanna Migrate'
EMAIL_TEMPLATE_CONTACT_FORM = 'aa8f9c9d-9e1a-441a-9142-9839e8a858f9'

# TRACKING EVENTS SETTINGS
TRACKING_EVENT_SENT_SUPPORT_MESSAGE = 'sent_support_message'
TRACKING_EVENT_LOGGED_IN = 'logged_in'
TRACKING_EVENT_SIGNED_UP = 'signed_up'
TRACKING_EVENT_REQUESTED_PASSWORD_RESET = 'requested_password_reset'
TRACKING_EVENT_PLACED_ORDER = 'placed_order'
TRACKING_EVENT_VIEWED_CONTENT = 'viewed_content'
TRACKING_EVENT_PROCEEDED_TO_PAYMENT = 'proceeded_to_payment'
