"""
Django settings for the wannamigrate project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import pytz
from celery.schedules import crontab
from django.utils.translation import ugettext_lazy as _
from .local import *


#########################################
# GENERAL SYSTEM CONFIGURATIONS
#########################################
# Base app path
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# URLs
if IS_PROD:
    BASE_URL = 'https://www.wannamigrate.com'
    BASE_URL_SECURE = 'https://www.wannamigrate.com'
else:
    BASE_URL = 'http://localhost:8087'
    BASE_URL_SECURE = 'http://localhost:8087'

# Access restrictions
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "wannamigrate.com",
    "www.wannamigrate.com",
]

INTERNAL_IPS = (
    "localhost",
    "127.0.0.1",
)

# Path of wsgi app
WSGI_APPLICATION = 'wannamigrate.wsgi.application'

# The base URL Conf
ROOT_URLCONF = 'wannamigrate.urls'


#########################################
# INTERNATIONALIZATION AND LOCALIZATION
#########################################
LANGUAGES = (
    ('en', _('English')),
    ('pt', _('Portuguese')),
)

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Australia/Sydney'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = False

LOCALE_PATHS = (
    os.path.join(BASE_DIR, '..', 'locale'),
)


#########################################
# PATHS FOR STATIC, UPLOAD and TEMPLATES
#########################################
# Global UPLOAD folder
MEDIA_ROOT = os.path.join(BASE_DIR, '..', 'upload')
MEDIA_URL = '/upload/'

# Static Files paths
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, '..', "static")


#########################################
# TEMPLATE SETTINGS
#########################################

# Template Context Processors
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, '..', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wannamigrate.core.context_processors.add_global_template_data'
            ],
        },
    },
]


#########################################
# MIDDLEWARES
#########################################
MIDDLEWARE_CLASSES = (
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware'
)


#########################################
# DJANGO APPS REQUIRED
#########################################
# Application definition
DEFAULT_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)
THIRD_PARTY_APPS = (
    'stdimage',
    'compressor',
)
LOCAL_APPS = (
    'wannamigrate.core',
    'wannamigrate.landing',
    'wannamigrate.member',
    'wannamigrate.order',
)

INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY_APPS + LOCAL_APPS


#########################################
# COMPRESSOR SETTINGS (for static css and js)
#########################################
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)
COMPRESS_ENABLED = False
COMPRESS_OFFLINE = True
COMPRESS_CSS_FILTERS = (
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.rCSSMinFilter'
)
COMPRESS_STORAGE = 'compressor.storage.GzipCompressorFileStorage'
HTML_MINIFY = True
EXCLUDE_FROM_MINIFYING = ('/admin/')


#########################################
# LOGGING / DEBUG SETTINGS
#########################################
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/wannamigrate/debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}


#########################################
# WANNAMIGRATE APP SETTINGS
#########################################

# Model choices
GENDER_CHOICES = (
    ('F', _('Female')),
    ('M', _('Male'))
)
BOOLEAN_CHOICES = (
    (True, _('Yes')),
    (False, _('No'))
)
TIMEZONES = [(tz, tz) for tz in pytz.common_timezones]
