# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 05:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import wannamigrate.core.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20161228_1551'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=1, null=True, verbose_name='gender')),
                ('avatar', stdimage.models.StdImageField(blank=True, null=True, upload_to=wannamigrate.core.util.CustomUploadToAutoSlugClassNameDir('user'), verbose_name='photo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('is_newsletter_subscribed', models.BooleanField(default=True, verbose_name='subscribed to newsletter')),
                ('payment_api_customer_uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='payment API Customer UUID')),
                ('staff_notes', models.TextField(blank=True, null=True, verbose_name='staff notes')),
                ('referral_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='referral code')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Country', verbose_name='country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'default_permissions': [],
                'permissions': (('admin_add_member', 'ADMIN: Can add member'), ('admin_change_member', 'ADMIN: Can change member'), ('admin_delete_member', 'ADMIN: Can delete member'), ('admin_view_member', 'ADMIN: Can view members')),
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('payment_api_method_uuid', models.CharField(max_length=200, verbose_name='API Payment uuid')),
                ('is_default', models.BooleanField(default=True, verbose_name='is default')),
                ('card_brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='card brand')),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True, verbose_name='card last4')),
                ('card_expiry_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='card exp month')),
                ('card_expiry_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='card exp year')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member', verbose_name='member')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.PaymentType', verbose_name='payment type')),
            ],
            options={
                'default_permissions': [],
                'ordering': ['-is_default'],
            },
        ),
    ]
