# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import wannamigrate.core.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20170330_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('html_content', models.TextField(verbose_name='html content')),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to=wannamigrate.core.util.CustomUploadToAutoSlugClassNameDir('title'), verbose_name='image')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country', verbose_name='country')),
            ],
            options={
                'default_permissions': [],
                'permissions': (('admin_add_post', 'ADMIN: Can add post'), ('admin_change_post', 'ADMIN: Can change post'), ('admin_delete_post', 'ADMIN: Can delete post'), ('admin_view_post', 'ADMIN: Can view posts')),
            },
        ),
    ]
