# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=1, max_length=180, verbose_name='description'),
            preserve_default=False,
        ),
    ]
