# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-13 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import stdimage.models
import wannamigrate.core.util


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_1',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=wannamigrate.core.util.CustomUploadToAutoSlugClassNameDir('image_description_1'), verbose_name='image 1'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_2',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=wannamigrate.core.util.CustomUploadToAutoSlugClassNameDir('image_description_2'), verbose_name='image 2'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_description_1',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='image 1 description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image_description_2',
            field=models.CharField(default=1, max_length=200, verbose_name='image 2 description'),
            preserve_default=False,
        ),
    ]
