# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-13 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20170713_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_description_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='image 1 description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_description_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='image 2 description'),
        ),
    ]
