# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='gross total')),
                ('net_total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='net total')),
                ('gst', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='GST')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='discount')),
                ('discount_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='discount code')),
                ('payment_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='payment fees')),
                ('shipping_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='shipping fees')),
                ('is_fulfilled', models.BooleanField(default=False, verbose_name='is fulfilled')),
                ('payment_api_transaction_uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='payment API Transaction UUID')),
                ('client_notes', models.TextField(blank=True, null=True, verbose_name='client notes')),
                ('staff_notes', models.TextField(blank=True, null=True, verbose_name='staff notes')),
                ('is_pending_recalculation', models.BooleanField(default=False, verbose_name='is pending recalculation')),
            ],
            options={
                'permissions': (('admin_change_order', 'ADMIN: Can change order'), ('admin_view_order', 'ADMIN: Can view orders'), ('admin_swap_wines', 'ADMIN: Can swap subscription wines')),
                'default_permissions': [],
                'ordering': ['-modified_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('payment_api_transaction_uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='payment api transaction uuid')),
                ('full_api_response', models.TextField(blank=True, null=True, verbose_name='full API response')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='order')),
            ],
            options={
                'default_permissions': [],
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('product_name', models.CharField(max_length=200, verbose_name='product name')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='product price ($)')),
                ('quantity_ordered', models.PositiveSmallIntegerField(default=1, verbose_name='qty ordered')),
                ('quantity_fulfilled', models.PositiveSmallIntegerField(default=0, verbose_name='qty fulfilled')),
                ('quantity_cancelled', models.PositiveSmallIntegerField(default=0, verbose_name='qty cancelled')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='order')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('name', models.CharField(max_length=45, verbose_name='name')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('name', models.CharField(max_length=45, verbose_name='name')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('name', models.CharField(max_length=15, verbose_name='code')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='discount %')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='discount $')),
                ('expiry_date', models.DateField(verbose_name='expiry date')),
            ],
            options={
                'permissions': (('admin_add_promo_code', 'ADMIN: Can add promo code'), ('admin_change_promo_code', 'ADMIN: Can change promo code'), ('admin_delete_promo_code', 'ADMIN: Can delete promo code'), ('admin_view_promo_code', 'ADMIN: Can view promo code')),
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderStatus', verbose_name='order status'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderStatus', verbose_name='order status'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.PaymentType', verbose_name='payment type'),
        ),
    ]
