# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_quiz_answers'),
        ('order', '0003_auto_20161228_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price ($)')),
            ],
            options={
                'permissions': (('admin_add_product', 'ADMIN: Can add product'), ('admin_change_product', 'ADMIN: Can change product'), ('admin_delete_product', 'ADMIN: Can delete product'), ('admin_view_product', 'ADMIN: Can view products')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('expiry_date', models.DateTimeField(verbose_name='expiry date')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member', verbose_name='member')),
            ],
            options={
                'permissions': (('admin_add_subscription', 'ADMIN: Can add subscription'), ('admin_change_subscription', 'ADMIN: Can change subscription'), ('admin_delete_subscription', 'ADMIN: Can delete subscription'), ('admin_view_subscription', 'ADMIN: Can view subscription')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('name', models.CharField(max_length=45, verbose_name='name')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_fulfilled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_pending_recalculation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_fees',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity_cancelled',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity_fulfilled',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity_ordered',
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_gift_enabled',
            field=models.BooleanField(default=True, verbose_name='enabled for gifts'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_oneoff_enabled',
            field=models.BooleanField(default=True, verbose_name='enabled for one-offs'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_subscription_enabled',
            field=models.BooleanField(default=True, verbose_name='enabled for subscriptions'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='usage_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='usage limit'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.SubscriptionStatus', verbose_name='subscription status'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Product', verbose_name='product'),
            preserve_default=False,
        ),
    ]
