# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20170415_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Subscription', verbose_name='subscription'),
            preserve_default=False,
        ),
    ]
