# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expiry date'),
        ),
    ]
