# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-15 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20170416_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='is_gift_enabled',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='is_oneoff_enabled',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='is_subscription_enabled',
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='is enabled'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='usage count'),
        ),
    ]
