# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-08 13:29
from __future__ import unicode_literals

from django.db import migrations


def add_extra_products(apps, schema_editor):

    # Get model to use (historical version)
    Product = apps.get_model("order", "Product")

    # Insert Records
    product = Product()
    product.id = 2
    product.name = '3-Month Unlimited Access'
    product.price = 7.00
    product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20170615_2146'),
    ]

    operations = [
        migrations.RunPython(add_extra_products),
    ]
