# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 10:52
from __future__ import unicode_literals
from django.utils.text import slugify
from django.db import migrations


def slugify_countries(apps, schema_editor):

    # Get models to use (historical version)
    Country = apps.get_model("core", "Country")

    countries = Country.objects.all()
    for country in countries:
        country.slug = slugify(country.name)
        country.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161228_1551'),
    ]

    operations = [
        migrations.RunPython(slugify_countries),
    ]
