# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-26 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170330_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='is enabled')),
                ('sort_order', models.PositiveSmallIntegerField(default=1, verbose_name='sort order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
