# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-26 00:55
from __future__ import unicode_literals

from django.db import migrations


def stage_initial_values(apps, schema_editor):

    # Get model to use (historical version)
    Stage = apps.get_model("core", "Stage")

    stage = Stage()
    stage.name = 'Deciding/Planning'
    stage.is_enabled = True
    stage.sort_order = 1
    stage.save()

    stage = Stage()
    stage.name = 'Applying For A Visa'
    stage.is_enabled = True
    stage.sort_order = 2
    stage.save()

    stage = Stage()
    stage.name = 'Waiting For A Visa'
    stage.is_enabled = True
    stage.sort_order = 3
    stage.save()

    stage = Stage()
    stage.name = 'Visa Approved'
    stage.is_enabled = True
    stage.sort_order = 4
    stage.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stage'),
    ]

    operations = [
        migrations.RunPython(stage_initial_values),
    ]
