# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-26 01:15
from __future__ import unicode_literals

from django.db import migrations


def visa_initial_values(apps, schema_editor):

    # Get model to use (historical version)
    Visa = apps.get_model("core", "Visa")

    visa = Visa()
    visa.name = 'Student Visa'
    visa.is_enabled = True
    visa.sort_order = 1
    visa.save()

    visa = Visa()
    visa.name = 'Skilled Worker Visa'
    visa.is_enabled = True
    visa.sort_order = 2
    visa.save()

    visa = Visa()
    visa.name = 'Work Holiday Visa'
    visa.is_enabled = True
    visa.sort_order = 3
    visa.save()

    visa = Visa()
    visa.name = 'Business/Investor Visa'
    visa.is_enabled = True
    visa.sort_order = 4
    visa.save()

    visa = Visa()
    visa.name = 'Partner/Parents Visa'
    visa.is_enabled = True
    visa.sort_order = 5
    visa.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_visa'),
    ]

    operations = [
        migrations.RunPython(visa_initial_values),
    ]
